#
# Generated by the NeXT Project Builder.
#
# NOTE: Do NOT change this file -- Project Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = NeXTGo

PROJECTVERSION = 1.1
LANGUAGE = German

APPICON = NeXTGo.tiff
DOCICONS = NeXTGoFile.tiff

GLOBAL_RESOURCES = NeXTGo.nib Background.tiff NeXTGo.tiff\
                   NeXTGoFile.tiff intergo.dct Makefile\
                   Makefile.postamble NeXTGo.background-2.0.draw\
                   NeXTGo.background.draw NeXTGoHelp.rtf

CLASSES = AutoWidthMatrix.m Board.m ClickCell.m Controller.m\
          GameInspectorPanel.m GoApp.m GoServer.m GoWindow.m\
          MatrixScrollView.m MiscString.m MiscStringFields.m\
          MiscStringInsertion.m MiscStringModification.m\
          MiscStringSearching.m ServerList.m

HFILES = AutoWidthMatrix.h Board.h ClickCell.h Controller.h\
         GameInspectorPanel.h gnugo.h GoApp.h godict.h GoServer.h\
         GoWindow.h history.h igs.h MatrixScrollView.h MiscString.h\
         patterns.h ServerList.h shared.h smartgo.h smgcom.h

MFILES = igsglue.m igssocket.m NeXTGo_main.m

CFILES = count.c countlib.c eval.c exambord.c findnext.c findopen.c\
         findpatn.c findsavr.c findwinr.c fioe.c genmove.c godict.c\
         igsparse.c initmark.c matchpat.c opening.c openregn.c\
         random.c score.c seed.c sethand.c smartgoeval.c\
         smartgoparse.c smartgotree.c suicide.c

OTHERSRCS = comment.header COPYING Documentation.gnugo igs.protocol\
            README README.gnugo


MAKEFILEDIR = /NextDeveloper/Makefiles/app
MAKEFILE = app.make
INSTALLDIR = $(HOME)/Apps
INSTALLFLAGS = -c -s -m 755
SOURCEMODE = 444

ICONSECTIONS =	-sectcreate __ICON app NeXTGo.tiff \
		-sectcreate __ICON NeXTGoFile NeXTGoFile.tiff

LIBS = -lMedia_s -lNeXT_s
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)


LIBRARY_PATHS = -L
PB_LDFLAGS = -v


-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
