/* Generated by the NeXT Project Builder 
   NOTE: Do NOT change this file -- Project Builder maintains it.
*/

#import "GoApp.h"

void main(int argc, char *argv[]) {

    NSAutoreleasePool *myPool = [[NSAutoreleasePool alloc] init];

    [GoApp sharedApplication];
    if ([NSBundle loadNibNamed:@"NeXTGo.nib" owner:NSApp])
	    [NSApp run];
	    
    [NSApp release];

    [myPool release];

    exit(0);
}
